-- Migration: Add Commish Code registration system
-- Commish Codes are generated by admins and valid for 24 hours
-- New members must provide a valid code to register

CREATE TABLE IF NOT EXISTS commish_codes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(16) NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL,
    created_by INT NULL,
    is_active TINYINT(1) DEFAULT 1,
    INDEX idx_code_active (code, is_active),
    INDEX idx_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
